name: elshigh
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  printing: ^5.13.4
  rename: ^3.0.2
  share_plus: ^10.0.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon.png
